### ISSUE TITLE
Remove ads off of landing pages

### ISSUE THREAD

**Issue by KyleSmith0905** [abass-dev/abassdev.com#1]
Hi!

Your website has a lot of ads, which is great if you're making good money from it. However, it would be embarrassing for a future recruiter to see your website and get shown all those ads.

Consider removing ads from areas that do not benefit the user, (such as your landing page and contact page that acts as your personal marketing).

I agree with ads (I never use an ad-block), you could keep them in your Shortcodes section since the user is benefiting personally from visiting that page. (idk, maybe this is the wrong way to look at it) :D

**Comment by abass-dev** [comment]
Thank you for your feedback, I also think about this and I'll fix it in the next commit!

**Comment by KyleSmith0905** [comment]
That was fast! Looks a lot better! 😀
